# -*- coding: utf-8 -*-
"""Arquivo Inicial - Tipos de Variaveis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fi29Z7mZElaHs76kJzDLTzzwnEGZaHX9
"""

faturamento = 1000

print('O faturamento da loja foi ' + faturamento)